version: "3.4"

services:
  api:
    image: gcr.io/savecrate/whatsmyhood-api:${WHATSMYHOOD_VERSION:-dev}
    container_name: whatsmyhood-api
    build: ./api
    ports:
      - "50005:5000"
    volumes:
      - ./api:/app
    env_file: ./api/.env
    stdin_open: true
    tty: true
